version: '3.8'

services:
  oracle-db:
    image: 232705206979.dkr.ecr.eu-west-2.amazonaws.com/beacons-oracle:latest
    container_name: oracle-db
    ports:
    - 1521:1521
    - 5500:5500

  etl:
    build:
      context: ./
    container_name: etl
