name: 'Dev Migration Pipeline'

on:
  # Allows manual running of the migration on the development environment
  workflow_dispatch:

jobs:
  run_migration:
    name: Run Beacons migration on dev
    runs-on: ubuntu-latest

    # Checkout repo, docker login for AWS ECR (Oracle DB), stand up Oracle DB, build/run ETL Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Run migration
        run: ./run-migration.sh
      - name: Stop containers
        if: always()
        run: |
          docker logs oracle-db
          docker-compose down