name: 'Dev Migration Pipeline'

on:
  # Allows manual running of the migration on the development environment
  workflow_dispatch:

jobs:
  run_migration:
    name: Run Beacons migration on dev
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2