name: 'Dev Migration Pipeline'

on:
  workflow_dispatch:

jobs:
  run_migration:
    name: Run Beacons migration
    runs-on: ubuntu-latest
    env:
      ENVIRONMENT: DEVELOPMENT
      API_BASIC_AUTH_USERNAME: ${{ secrets.DEV_API_BASIC_AUTH_USERNAME }}
      API_BASIC_AUTH_PASSWORD: ${{ secrets.DEV_API_BASIC_AUTH_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
      - name: Run migration
        run: ./run-migration.sh
      - name: Upload migration results
        uses: actions/upload-artifact@v2
        with:
          name: migration-results
          path: migration_results/
      - name: Check migration_results
        run: ls -al && ls -al migration_results/
      - name: Stop containers
        if: always()
        run: docker-compose down